name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Generate snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Rajguru-Aditya
          outputs: dist/github-contribution-grid-snake.svg

      - name: Push snake
        uses: crazy-max/ghaction-github-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: output
          build_dir: dist
