name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: Platane/snk@v3
        with:
          github_user_name: Rajguru-Aditya
          outputs: |
            dist/github-contribution-grid-snake.svg

      - uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*.svg"
          message: "Generate snake animation"
